 create table product (
       id bigint generated by default as identity (start with 1),
        price double not null,
        product_description varchar(255),
        product_name varchar(255),
        product_type varchar(255),
        primary key (id)
    );